# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Backtest Threshold Function
#'
#' This function computes cumulative returns.
#'
#' @param returns A numeric vector of returns.
#' @param indicator A numeric vector used as an indicator.
#' @param threshold A numeric threshold.
#' @param sell_below Logical, indicating sell decision.
#' @return A single numeric value corresponding to the adjusted cumulative return.
#' @export
backtest_threshold <- function(returns, indicator, threshold, sell_below) {
    .Call('_finutils_backtest_threshold', PACKAGE = 'finutils', returns, indicator, threshold, sell_below)
}

#' Run Backtest Without SMA
#'
#' Processes a DataFrame and parameter DataFrame to compute backtest results using
#' a unified backtesting function. The function applies the given threshold logic to each
#' indicator column specified in `params`.
#'
#' @param df DataFrame containing at least the `returns` column and indicator columns.
#' @param params DataFrame with parameters, including columns "variable" (indicator names)
#'   and "thresholds" (numeric thresholds).
#' @param sell_below Logical flag; if TRUE, sells when the indicator is below the threshold.
#' @return A numeric vector with backtest results for each row in `params`.
#' @export
opt_threshold <- function(df, params, sell_below = TRUE) {
    .Call('_finutils_opt_threshold', PACKAGE = 'finutils', df, params, sell_below)
}

#' Calculate Simple Moving Average (SMA)
#'
#' Computes the Simple Moving Average (SMA) for the numeric vector `x` using
#' a window of size `n`. For indices with insufficient data points, NA is returned.
#'
#' @param x Numeric vector for which the SMA is calculated.
#' @param n Window size (number of observations) used for the SMA calculation.
#' @return A numeric vector of the same length as `x` containing the SMA values.
#' @export
calculate_sma <- function(x, n) {
    .Call('_finutils_calculate_sma', PACKAGE = 'finutils', x, n)
}

#' Run Backtest with SMA Filtering
#'
#' Applies a simple moving average (SMA) filter to indicator columns before performing backtesting.
#' For each parameter row in `params`, the function calculates the SMA of the corresponding indicator
#' and then computes the backtest result using the unified backtesting function.
#'
#' @param df DataFrame containing at least the `returns` column and indicator columns.
#' @param params DataFrame with parameters, including "variable", "thresholds", and "sma_n" (window size for SMA).
#' @param sell_below Logical flag; if TRUE, sells when the SMA-filtered indicator is below the threshold.
#' @return A numeric vector of backtest results for each parameter set after SMA filtering.
#' @export
opt_with_sma_threshold <- function(df, params, sell_below = TRUE) {
    .Call('_finutils_opt_with_sma_threshold', PACKAGE = 'finutils', df, params, sell_below)
}

#' Combined Windowed Optimization with SMA Filtering
#'
#' Applies a window-based optimization to a DataFrame by slicing it into windows (either rolling or expanding)
#' and then performing SMA-based backtesting on each slice using [opt_with_sma_threshold]. The output is a list of
#' data frames binding the time stamp with the backtest results for each window.
#'
#' @param df DataFrame containing the data. Must include a `time` column and a `returns` column.
#' @param params DataFrame with parameters; expected to include columns "variable", "thresholds", and "sma_n".
#' @param window Integer specifying the window size (number of rows) to use for each optimization slice.
#' @param window_type A string to determine the window slicing method; either "rolling" (default) or "expanding".
#' @return A list of DataFrames, each with a time stamp and the corresponding backtest results for that window.
#' @export
wfo_combined <- function(df, params, window, window_type = "rolling") {
    .Call('_finutils_wfo_combined', PACKAGE = 'finutils', df, params, window, window_type)
}

